gitlab_tag: "latest"
gitlab_email_from: "{{ contact_email }}"
gitlab_email_display_name: "{{ gitlab_name }} notifications"

# controls mounting volumes atm
environment_type: test

gitlab_extra_config: "#no extra config"