- name: add secret/config backup command to cron
  cron:
    name: create a backup of secrets/configs
    special_time: daily
    job: docker exec -t gitlab /bin/sh -c 'umask 0077; tar cfz /secret/gitlab/backups/$(date "+etc-gitlab-\%s.tgz") -C / etc/gitlab --exclude=etc/gitlab/backups'

- name: add user data backup to cron
  cron:
    name: create a user data backup
    special_time: daily
    job: docker exec -t gitlab gitlab-rake gitlab:backup:create

- name: add old backup file cleanup to root crontab
  cron:
    name: remove old backup files
    minute: 30
    hour: 5
    job: tmpwatch -u 14d /srv/gitlab/data/backups /srv/gitlab/config/backups
  become: yes
